### ISSUE TITLE
[super] Extensions Registry First Pass

### ISSUE THREAD

**Issue by rufuspollock** [ckan/extensions.ckan.org#4]
We want to create an extensions registry - see https://github.com/ckan/ideas-and-roadmap/issues/22
## User stories

As a CKAN User I want to know what extensions exist and their status so that I can find ones I can use and know they are production ready (or not)

As a CKAN Developer I want to publish my extension so that others know it exists and can use it
## Implementation
- [ ] Determine metadata structure - #5 
- [x] Automatically collect information - #8
- [x] Create a page to display and allow searching (front page) - #2 
- [x] Page for each individual extension - #6
- [x] Have a process for submitting new information (and correcting old) - #7
